---

- name: ensure selenium_lib directories exist
  file: path={{ selenium_lib_dir }}/{{ item }} state=directory
  with_items:
      - ""
      - java

- name: transfer selenium_lib files to remote host
  copy: >
      src={{ role_path }}/../../../selenium-lib/{{ item.path }}
      dest={{ selenium_lib_dir }}/{{ item.path }}
      force=yes mode={{ item.mode }}
  with_items:
      - { path: 'geckodriver.tgz', mode: '0444' }
      - { path: 'selenium-server.jar', mode: '0444' }
      - { path: 'taas-xvfb-run.centos', mode: '0555' }
      - { path: 'user-extensions.js', mode: '0444' }
      - { path: 'java/hamcrest-core.jar', mode: '0444' }
      - { path: 'java/selenium-java.jar', mode: '0444' }
      - { path: 'java/selenium-server.jar', mode: '0444' }
