---
- name: Check registry existence
  shell: docker ps -a | grep "\s{{ docker_registry_image }}\s.*\s{{ docker_registry_name }}$"
  become: True
  register: docker_registry_check
  changed_when: False
  ignore_errors: True

- debug:
    var: docker_registry_check
    verbosity: 2

- name: Run registry server
  command: >
      docker run -d --restart=always
      -p {{ docker_registry_port }}:5000
      -v {{ docker_registry_volume_name }}:/var/lib/registry
      registry:2
  when: docker_registry_check|failed
  become: True
