- hosts: docker-build-server
  roles:
      - include_taas_vars
      - { role: docker_on_openstack, become: True }
  vars:
      docker_image: "{{ core_services.rsc_mgmt.image.name }}" 
      docker_dir: "{{ ansible_env.HOME }}/docker_rsc_mgmt"
      docker_file: Dockerfile.rsc_mgmt_api_server
      src_dirs:
          - bin
          - lib
          - lib/heat
          - log
          - log/openstack
          - log/server
          - public
          - public/stylesheets
          - routes
          - views
      src_files:
          - app.js
          - bin/www
          - default.json
          - heat_template.yaml
          - instance.yaml
          - lib/auth.js
          - lib/config.js
          - lib/heat/instance with floating IP.yaml
          - lib/httprequest.js
          - log/openstack/connections.log
          - log/server/connections.log
          - logfile.json
          - makecfg.py
          - package.json
          - public/stylesheets/style.css
          - routes/glance.js
          - routes/index.js
          - routes/nova.js
          - routes/orchestration.js
          - routes/taas.js
          - server_conf.yaml
          - test_openstack.sh
          - views/error.jade
          - views/index.jade
          - views/layout.jade
  tasks:
      - name: ensure docker base directory exists
        file:
            path: "{{ docker_dir }}"
            state: directory

      - name: ensure rsc_mgmt directories exist
        file:
            path: "{{ docker_dir }}/{{ item }}"
            state: directory
        with_items: "{{ src_dirs }}"

      - name: transfer rsc_mgmt files to remote host
        copy:
            src: "{{ playbook_dir }}/../rsc_mgmt_node-api/{{ item }}"
            dest: "{{ docker_dir }}/{{ item }}"
            mode: 0444
            force: yes
        with_items: "{{ src_files }}"

      - name: transfer docker file to remote host
        copy:
            src: "{{ playbook_dir }}/../docker/{{ docker_file }}"
            dest: "{{ docker_dir}}/{{ docker_file }}"
            mode: 0444
            force: yes

      - name: build docker image
        become: True
        command: docker build -t {{ docker_image }} -f {{ docker_file }} .
        args:
            chdir: "{{ docker_dir }}"
        tags:
            - skip_me

      - name: set docker registry
        set_fact:
            docker_registry_url: "{{ docker_registry_url | default('') }}"

      - name: push docker image (1)
        become: True
        command: "docker tag taas_rsc_mgmt_api_server {{ docker_registry_url }}/{{ docker_image }}"
        when: docker_registry_url != ""
        tags:
            - skip_me

      - name: push docker image (2)
        become: True
        command: "docker push {{ docker_registry_url }}/{{ docker_image }}"
        when: docker_registry_url != ""
        tags:
            - skip_me

